services:
  socialblog_backend:
    build: .
    ports:
      - 3333:3333
    env_file:
      - .env
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && node build/app.js"

  db:
    image: postgres:15
    container_name: socialblog_psql
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: socialblog_backend
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pgdata: