services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redisdata:/data
  socialblog_backend:
    build: .
    ports:
      - 3333:3333
    env_file:
      - .env
    depends_on:
      - db
    command: ["./command.sh"]

  db:
    image: postgres:15
    container_name: socialblog_psql
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: socialblog_backend
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"


volumes:
  pgdata:
  redisdata:
