### Request para logear al user
POST http://localhost:3333/api/login
Content-Type: application/json

{
  "email": "nicolasguarachi888@gmail.com",
  "password": "Nicolas-9090"
}

### Request para registro de user
POST http://localhost:3333/api/register
Content-Type: application/json

{
  "name": "UsopKing7",
  "email": "nicolasguarachi888@gmail.com",
  "password": "Nicolas-9090"
}

### Request para filtrar usuarios con el rol ADMIN or admin
GET http://localhost:3333/admin/usuarios/94ed23b9-dcec-40c1-9cb3-a5a16287c279/roles 
