### Request para reportar un comentrario
POST http://localhost:3333/api/user/7309ed09-44da-403e-b507-f569cd0a2224/comments/a098fcaa-3a31-4875-8d6d-aaf12070af9b
Content-Type: application/json

{
  "reason": "comentario de violacion de normas"
}

### Request para obtener todos los reportes
GET http://localhost:3333/admin/user/7309ed09-44da-403e-b507-f569cd0a2224/reports