### Request para logear al user
POST http://localhost:3333/api/login
Content-Type: application/json

{
  "email": "nicolasguarachi888@gmail.com",
  "password": "Nicolas-9090"
}

### Request para registro de user
POST http://localhost:3333/api/register
Content-Type: application/json

{
  "name": "UsopKing7",
  "email": "nicolasguarachi888@gmail.com",
  "password": "Nicolas-9090"
}

### Request para creacion de roles
POST http://localhost:3333/api/create/role/b244faf7-5122-44fb-8b52-68edb65d1952
Content-Type: application/json

{
  "name_role": "admin"
}

### Request para creacion de post => publicacion
POST http://localhost:3333/api/user/create-post/b244faf7-5122-44fb-8b52-68edb65d1952
Content-Type: application/json

{
  "title": "Proyecto nicolas => Backend",
  "content": "este es mi primer proyecto grande con muchas tegnologias nuevas"
}

### Request para actualizar el post segun el usuairo => update post
PATCH http://localhost:3333/api/user/61c96ca3-bbb0-4fab-89af-07f0adef7a87/update-post/22bd29c6-1daa-44b7-b598-d75316ea5b4b
Content-Type: application/json

{
  "title": "new title => 2",
  "content": "new content => 2"
}

### Request para obtener todos los Posts
GET http://localhost:3333/api/posts

### Request para ontener todos los posts de un usuario
GET http://localhost:3333/api/user/posts/b244faf7-5122-44fb-8b52-68edb65d1952

### Request para eliminar un post por usuario
DELETE http://localhost:3333/api/user/46140978-0352-49f0-af71-8907fcd8a77b/delete-post/9696a37f-4a43-424b-8675-3c645f61c456

### Requesta para actualizar un comentario
PATCH http://localhost:3333/api/user/b244faf7-5122-44fb-8b52-68edb65d1952/post/893c96c6-6e58-4f59-84e0-3753b01dd7ab/comment/3a6a2343-2431-4ae0-8880-628a7c6979d3/update-comment
Content-Type: application/json

{
  "content": "new comment para eliminar"
}

### Request para obtener todos los comentarios de un post
GET http://localhost:3333/api/posts/comments/893c96c6-6e58-4f59-84e0-3753b01dd7ab

### Request para eliminar un commentario
DELETE http://localhost:3333/api/user/b244faf7-5122-44fb-8b52-68edb65d1952/post/893c96c6-6e58-4f59-84e0-3753b01dd7ab/comment/3a6a2343-2431-4ae0-8880-628a7c6979d3/delete-comment

### Request para dar like a un post
POST http://localhost:3333/api/user/b244faf7-5122-44fb-8b52-68edb65d1952/post/893c96c6-6e58-4f59-84e0-3753b01dd7ab/like

### Request para eliminar el like
DELETE http://localhost:3333/api/user/b244faf7-5122-44fb-8b52-68edb65d1952/post/893c96c6-6e58-4f59-84e0-3753b01dd7ab/dislike

### Request para dar like a un comment
POST http://localhost:3333/api/user/b244faf7-5122-44fb-8b52-68edb65d1952/comment/0057c28c-c4a3-483b-b968-02ba507d91b8/like

### Request para eliminar like del comment
DELETE http://localhost:3333/api/user/b244faf7-5122-44fb-8b52-68edb65d1952/comment/0057c28c-c4a3-483b-b968-02ba507d91b8/dislike
